<?php
// require_once("text_ja.php");
?>
<!DOCTYPE html>
<html lang="ja">
<head>
        <meta charset="UTF-8">
        <meta name="author" content="ken kodama">
        <meta property="og:type" content="website">
        <meta property="og:description" content="<?php echo $this->trans->_('siteTitle') . "," .$this->trans->_('siteDesc') ?>">
        <meta property="og:title" content="<?php echo $this->trans->_('siteTitle') ?>">
        <meta property="og:url" content="https://ckeiba.appstarrocks.com/">
        <meta property="og:image" content="https://ckeiba.appstarrocks.com/images/anauma-kuruko408.png">
        <meta property="og:site_name" content="<?php echo $this->trans->_('siteTitle') ?>">
        <meta property="og:locale" content="ja_JP">
        <meta name="google-site-verification" content="kkR57VEj9LZJ3c5NwlWCrPDMuwQTbAEAEH6t0Jz2AC0" />
        <meta name="keywords" content="<?php echo $this->trans->_('siteTitle') ?>" />
        <meta name="description" content="<?php echo $this->trans->_('siteTitle') . "," .$this->trans->_('siteDesc') ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?php echo $this->trans->_('titleTag') ?></title>
        <link rel="alternate" hreflang="ja" href="https://ckeiba.appstarrocks.com/index.php">
        <link rel="shortcut icon" href="favicon.ico" >
        <link rel="stylesheet" href="https://code.jquery.com/mobile/1.4.0/jquery.mobile-1.4.0.min.css" />
        <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
        <script src="https://code.jquery.com/mobile/1.4.0/jquery.mobile-1.4.0.min.js"></script>
        <link rel="stylesheet" href="/css/style.css" />
<style>
.adSidebar {
    margin: auto;
    max-height: 600px;
    width: 320px;
    /*width: 302px;*/
}
.adContent {
    margin: auto;
    width: 320px;
    /*width: 300px;*/

    @media #{$small-break} {
        width: 320px;
    }
    @media #{$large-break} {
        width: 730px;
    }
}
.body1{
 text-align:left;
}
</style>
 </head>
<body>
<?php include_once("analyticstracking.php") ?>
<div id="content" data-role="content" >
    <div id="header" class="ui-bar" data-role="header" data-position="fixed">
        <h2>Cassandra2016kkのAI予想(地方競馬)</h2>
        <a  href="/Index">HOME</a>
        <a  href="/Index/Recover" style="margin-right:40px" ><?php echo $this->trans->_('label_recover') ?></a>
    </div>
    <div class="body1">
        <div><img src="/images/anauma-kuruko408.png" alt="anamuma-kuruko" /></div>
        <h4> <?php echo $this->trans->_('siteTitle') ?>
        <div class="about"><?php  echo $this->trans->_('siteDesc') ?></div></h4>
        <h4><?php echo $this->trans->_('label_senryu') ?>:</h4>
        <h4>
        <a href="https://twitter.com/kenchan_baken"><img src="/images/cassandra2016.png" alt="kenchanbaken" style="width:40px; height:40px" /></a> &lt;  <?php echo $this->senryu?>
        </h4>
    </div>
	
		<div id='raceList'>
              <?php
                  $contents="";
                  $file_path=$this->public_dir."/yosou/".$this->race_id . ".php";
                  if(!file_exists($file_path)){
                   echo "ma da dayo";  
                  }else{
                   $contents = file_get_contents($file_path);
                   echo  $contents;         
                  }       
                ?>
        </div>
        <div><H4>box</H4>
        <?php
                  $file_path=$this->public_dir."/yosou/".$this->race_id . "_box.txt";
                  $contents = file_get_contents($file_path);
                  echo  $contents;
                ?>
        </div>
    <hr/>

<hr/>
<?php require_once("amazon.php");?>
            <div data-role="footer" >
                <p><?php echo $this->trans->_('notes') ?></p>
                 <h4>
				<a rel="author" href="http://developer.appstarrocks.com/" ><?php echo $this->trans->_('copyright')  ?><a>
</h4>

            </div><!--footer-->
        </div><!--content-->
<script>
$("a").attr({ "data-ajax":"false" });
</script>
</body>
</html>

